### ISSUE TITLE
english version for Readme file

### ISSUE THREAD

**Issue by imakiro** [santos82/LFS201#1]
hello,

I'm looking to have an offline version of the LFS 201 course in offline format, unfortunately for me I don't understand spanish.
Is there a way for this to be available in english?

**Comment by s-nt-s** [comment]
Hi

This script automatizes the text extraction from the online course and its conversion to a single clean offline html, so you need to have acces to the online course in order to generate the offline version.

Can you login in the LFS201 online course?

In that case you have to:
1. Install in `chromium` (or `chrome`) the extension from `chrome` directory
2. Visit all pages of the course to save the htmls in your local drive (uncomment the line 68 of `chrome/content/js.js` if you want automatice most of the navigation, but anyway you have to visit popups manually)
3. Execute `run.sh` to move the htmls (edit line 6 of `run.sh` for that), clean an join it

As the `.py` files search spanish words to fix mistakes and find keys words this part of the process probably don't have effect (In fact, you should remove from `join.py` lines from 391 to 433) but the script should work enough to you have a readable single html with the course information.

**Comment by imakiro** [comment]
Ok, I did all this and the documents are indeed saved locally, but the automated next page navigation doesn't work.

**Comment by imakiro** [comment]
hello !
I edited join.py to remove check for spanish words, but I'm kind'of confused : I made the script run and auto navigate to the next page by changing line 68 of js.js to press on my next buton that had another number than you.
Everything has been downloaded in ~/Downloads , I the edited the run.sh to reflect that and there was an unmentionned dependency for python-bs that I installed. 
But in the end I did not get a valid sigle HTMLfile.

`LFS201/out$ cat LFS201.html 
<!DOCTYPE html>
<html>
  <head>
    <title>LFS201</title>
    <meta charset="utf-8"/>
    <link href="rec/main.css" rel="stylesheet" type="text/css"/>
  </head>
  <body>
    <div class="content">
    </div>
  </body>
</html>
`

**Comment by s-nt-s** [comment]
Probably the spanish key words are more important than I remembered.

There are two steps:
1. `clean.py` clean the downloaded html and save the result in `html/clean`
2. `join.py` join all the clean html in `out/LFS201.html`

If step 1 is ok you should have in `htrml/clean` htmls simplers than the html in `html/ori`. If step 1 is not ok the html from `htrml/clean` will be equals as the html from `html/ori`

If step 2 was ok you would have the full course inside `<div class="content">` of `out/LFS201.html` but if step 2 is not ok (or sptep 1 was not ok) you have a empty `<div class="content">`

Do you know python? The only solution is change the code to work with the english course instead of the course spanish.

Also, it the `name` of the `next button` is different in the english version I can't be sure about if other selectors I use to find the parse html (for example: `div.ttxt` in `clean.py` etc) could work in the english version.

**Comment by kanner** [comment]
the project works fine on English version of LFS201 with some minimal patches -- check my fork and ask questions if you still have them
